cask_args appdir: '/Applications'
tap 'homebrew/bundle'

cask '1Password'
cask 'raycast'
cask 'vlc'
cask 'zed'
cask 'zoom'
cask 'obsidian'
cask 'alacritty'
cask 'docker'
cask 'tailscale'
cask 'lens'
cask 'font-jetbrains-mono-nerd-font'
cask 'windows-app'
cask 'rectangle'
cask 'microsoft-office'
cask 'logi-options-plus'
cask 'logitune'
cask 'firefox'
