set nu rnu
set pastetoggle=<F3>

" Search and replace word under cursor using F4
nnoremap <F4> :%s/<c-r><c-w>/<c-r><c-w>/gc<c-f>$F/i

" set tab switching to F7 & F8 Open in new tab to <C_n>
nnoremap <F7> :tabp
nnoremap <F8> :tabn
nnoremap <C-n> :tabe
